### ISSUE TITLE
Unable to see view Data Frame after last update on 04/09/2024

### ISSUE THREAD

**Issue by jmmferrao** [microsoft/vscode-data-wrangler#274]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

Cannot open a data frame when trying to view the data with data wrangler. 

This is the message that I got: Received malformed content: {"name": "KeyError", "message": "'38e8d628-6b75-4cd7-a11f-b54dcff88ce3'", "stack": "Traceback \u001b[1;36m(most recent call last)\u001b[0m:\n\u001b[1;36m File \u001b[1;32m<string>:56\u001b[1;36m in \u001b[1;35m__DW_DEBUG_WRAPPER__\u001b[1;36m\n\u001b[1;31mKeyError\u001b[0m\u001b[1;31m:\u001b[0m '38e8d628-6b75-4cd7-a11f-b54dcff88ce3'\n"}

## Steps to reproduce:

1. Tried to run same code that I had before but it does no show. DW telemetry data:

[
  {
    "name": "Activate",
    "properties": {
      "WranglerHost": "vscode",
      "configurations": "{\"dataWrangler.debug\":true,\"dataWrangler.enabledFileTypes\":{\"csv\":true,\"tsv\":true,\"parquet\":true,\"xlsx\":true,\"xls\":true},\"dataWrangler.startInEditModeForNotebookEntrypoints\":false,\"dataWrangler.columnInsights.displayOnOpen\":true,\"dataWrangler.useRelativePath\":false,\"dataWrangler.experiments.autoDetectCsvDelimiter\":true,\"dataWrangler.experiments.fastCsvParsing\":true,\"dataWrangler.experiments.useJupyterProposedAPI\":true,\"dataWrangler.experiments.copilot.enabled\":false}",
      "abexp.assignmentcontext": "vsliv368:30146709;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;asynctok:30898717;dsvsc020:30976470;dwaa612cf:30983454;jg8ic977:31013176;dvdeprecation:31068756;dwnewjupyter:31046869;"
    },
    "measurements": {
      "duration": 0.012
    }
  },
  {
    "name": "LaunchDataWrangler",
    "properties": {
      "WranglerHost": "vscode",
      "entryPoint": "JupyterDataViewer",
      "format": "py",
      "viewMode": "dataViewer",
      "abexp.assignmentcontext": "vsliv368:30146709;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;asynctok:30898717;dsvsc020:30976470;dwaa612cf:30983454;jg8ic977:31013176;dvdeprecation:31068756;dwnewjupyter:31046869;",
      "sessionUriHash": "8186fe1a6c26da2c31e5a830d2161f9369ce81c6f35d8f86270fd04fda41b648",
      "originalUriHash": "246e656b4d9b11a29d2127cace0d8899f48bb83d0b52f38337e288ae0a526b74"
    }
  },
  {
    "name": "PackageDependenciesResolved",
    "properties": {
      "WranglerHost": "vscode",
      "installed": "{\"pandas\":\"2.1.1\",\"pyarrow\":\"15.0.1\"}",
      "required": "{\"pandas\":\"1.2.0\"}",
      "unsatisfied": "[]",
      "abexp.assignmentcontext": "vsliv368:30146709;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;asynctok:30898717;dsvsc020:30976470;dwaa612cf:30983454;jg8ic977:31013176;dvdeprecation:31068756;dwnewjupyter:31046869;",
      "sessionUriHash": "8186fe1a6c26da2c31e5a830d2161f9369ce81c6f35d8f86270fd04fda41b648",
      "originalUriHash": "246e656b4d9b11a29d2127cace0d8899f48bb83d0b52f38337e288ae0a526b74",
      "currentViewMode": "dataViewer"
    }
  },
  {
    "name": "OperationCodeExecutionFailed",
    "properties": {
      "WranglerHost": "vscode",
      "dataFrameType": "pandas",
      "telemetrySource": "startSession",
      "operationKey": "Variable",
      "abexp.assignmentcontext": "vsliv368:30146709;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;asynctok:30898717;dsvsc020:30976470;dwaa612cf:30983454;jg8ic977:31013176;dvdeprecation:31068756;dwnewjupyter:31046869;",
      "sessionUriHash": "8186fe1a6c26da2c31e5a830d2161f9369ce81c6f35d8f86270fd04fda41b648",
      "originalUriHash": "246e656b4d9b11a29d2127cace0d8899f48bb83d0b52f38337e288ae0a526b74",
      "currentViewMode": "dataViewer"
    },
    "measurements": {
      "shapeBeforeRows": 0,
      "shapeBeforeColumns": 0,
      "codeGenTimeInMS": 0,
      "codeExecTimeInMS": 37
    }
  },
  {
    "error": {
      "message": "dataLoadFailedError",
      "stack": "Error: dataLoadFailedError\n    at e.raiseError (c:\\Users\\1151827\\.vscode\\extensions\\ms-toolsai.datawrangler-1.8.0\\out\\extension.js:2:426208)\n    at e.<anonymous> (c:\\Users\\1151827\\.vscode\\extensions\\ms-toolsai.datawrangler-1.8.0\\out\\extension.js:2:398441)\n    at c:\\Users\\1151827\\.vscode\\extensions\\ms-toolsai.datawrangler-1.8.0\\out\\extension.js:2:387867\n    at Object.next (c:\\Users\\1151827\\.vscode\\extensions\\ms-toolsai.datawrangler-1.8.0\\out\\extension.js:2:387972)\n    at o (c:\\Users\\1151827\\.vscode\\extensions\\ms-toolsai.datawrangler-1.8.0\\out\\extension.js:2:386686)"
    },
    "properties": {
      "WranglerHost": "vscode",
      "errorCode": "dataLoadFailedError",
      "innerError": "Start session > Failed to execute code",
      "operationKey": "Variable",
      "failedDuringCodeExecution": "true",
      "inputErrors": "{}",
      "abexp.assignmentcontext": "vsliv368:30146709;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;asynctok:30898717;dsvsc020:30976470;dwaa612cf:30983454;jg8ic977:31013176;dvdeprecation:31068756;dwnewjupyter:31046869;",
      "sessionUriHash": "8186fe1a6c26da2c31e5a830d2161f9369ce81c6f35d8f86270fd04fda41b648",
      "originalUriHash": "246e656b4d9b11a29d2127cace0d8899f48bb83d0b52f38337e288ae0a526b74",
      "currentViewMode": "dataViewer"
    }
  }
]

# Diagnostic data

-   Jupyter extension version: 2024.7.0
-   Python extension version: 2024.12.3
-   .NET Install Tool for Extension Authors extension version: 2.1.5
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "2.1.1",
    "pyarrow": "15.0.1"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

Extension version: 1.8.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (4.35GB free)|
|Process Argv|--crash-reporter-id e6e70bc1-19c7-4c9c-a4f6-7841285c762a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by pwang347** [comment]
Hi @jmmferrao, does this issue still happen consistently for you after reloading VS Code?

**Comment by JoseMFerrao** [comment]
Hello, unfortunately yes. Somehow everything works fine if I put some break points along the code and use the extension every 100 lines or so, but if I try to use the extension for the first time at line 700 for instance, I still get the same error...

**Comment by pwang347** [comment]
Hi @JoseMFerrao thanks for confirming. You mentioned that this only started happening on 9/4/2024. Could you please share what the most recent working version is for you out of this list?

<img width="191" alt="image" src="https://github.com/user-attachments/assets/486924d4-30b2-4d61-b6b3-1e172761bd57">

If you click "Switch to pre-release version" on the extension page you can install more granular versions:
![image](https://github.com/user-attachments/assets/aefac664-0170-40b4-b79a-7e767af9574c)

Then from here you can install with
<img width="283" alt="image" src="https://github.com/user-attachments/assets/a47e36f9-da43-4821-be18-1696b266cf1f">

Thanks!

**Comment by JoseMFerrao** [comment]
Hello @pwang347! 

The most recent working version for me is 1.6.0. 

For now I can manage this limitation with the break points along the code and if needed I will switch back to the older version.

Thank you very much for the help and support!

**Comment by JoseMFerrao** [comment]
Hello @kycutler!

I do not want to point you in the wrong direction, so let me start by saying that I have the auto update option turned on for all Microsoft extensions, including data wrangler.

Having said that, I did not willingly decided to make use of pre-realease versions. Thus, unless the auto update feature installed one of those pre-realease versions automatically, I did not try any of them.

**Comment by kycutler** [comment]
@JoseMFerrao understood, thank you for the clarification -- would you be willing to install the pre-release versions manually and see if they have the issue as well? There are many changes between versions 1.6.0 and 1.8.0, so narrowing it down to a specific 1.7.x pre-release version would help us a lot to identify the cause of the issue. You can always switch back to a stable version after.

**Comment by JoseMFerrao** [comment]
@kycutler I will try to find the time to test the pre-release versions and let you know if I can narrow the issue to one of those pre-released versions!

**Comment by shsnyder** [comment]
I have recently started to experience this error as well, with the same stack trace.
I am running a regular Python program, not a jupyter notebook.

Whenever I try to visualize a dataframe or dictionary I see this screen.
![Image](https://github.com/user-attachments/assets/1dd34dbe-e9d2-4cee-bd27-dca7afce1528)

I am on a Mac running MacOS 14.7 Sonoma.

Let me know if I can provide any additional information.

VSCode 
Version: 1.94.2 (Universal)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0


# Diagnostic data

-   Jupyter extension version: 2024.9.1
-   Python extension version: 2024.16.1
-   .NET Install Tool for Extension Authors extension version: 2.2.0
-   Python package dependencies:

```json
{
  "installed": {
    "pandas": "1.3.5"
  },
  "required": {
    "pandas": "1.2.0"
  },
  "unsatisfied": []
}
```

-   Entrypoint: JupyterDataViewer
-   Active mode: dataViewer

**Comment by kycutler** [comment]
Hi @shsnyder, what version of Data Wrangler are you using? Would you be able to try the pre-release versions 1.7.0 / 1.7.1 / 1.7.2 to help us narrow down when the issue was introduced?

**Comment by shsnyder** [comment]
After the weekend it seems to be working again. There seems to be some environmental issue that seems to be causing this intermittently as it started to fail in the middle of a working session.
Coming in to work on Monday and trying several previous releases (and pre-releases) I did not see the issue.
Hopefully you can get a clue from the stack trace message in the failure.

**Comment by shsnyder** [comment]
It has magically reoccurred. 
Here is the explicit warning popup within VSCode.
![Image](https://github.com/user-attachments/assets/affa789f-6881-4e72-9794-23a271503c4a)


I tried a number of pre-release versions (1.71, 1.72) with the same problem as well as with 1.10.
It looks like it is an interaction with the latest VSCode version rather than a code change that was made in the extension.

**Comment by FangyangJz** [comment]
OS: Kubuntu 24.04.2 LTS x86_64

VSCode
Version: 1.97.2
Commit: e54c774e0add60467559eb0d1e229c6452cf8447
Date: 2025-02-12T23:20:35.343Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.97.2 Chrome/128.0.6613.186 Electron/32.2.7 Safari/537.36

Identifier
ms-toolsai.datawrangler
Version
1.18.2
Last Updated
2025-02-15, 02:08:38

Failed to load the data frame: UnknownError: Received malformed content: {"name":"KeyError","message":"'147c4626-9f67-4ce0-9c5e-f5089dad3924'","stack":"  File \"<string>\", line 77, in __DW_DEBUG_WRAPPER__\n"}

**Comment by pwang347** [comment]
Hi @FangyangJz, could you please provide the same information requested [here](https://github.com/microsoft/vscode-data-wrangler/issues/408#issuecomment-2658091093)?

Thanks!
